// components/CellOutput.tsx
import type { ExecResult } from "@/lib/kernel";
import {
  AlertTriangle,
  CheckCircle2,
  Code2,
  Image,
  Loader2,
  Terminal,
} from "lucide-react";

// ─── ANSI stripping ───────────────────────────────────────────────────────────
// Removes ANSI escape sequences (colors, cursor moves, etc.) that the kernel
// sends back as terminal output. Without this they appear as raw garbage like
// [31m-----------[39m or [32m      9[39m in the output panel.
const ANSI_RE = /\x1b\[[0-9;]*[a-zA-Z]|\x1b\][^\x07]*\x07|\x1b[()][AB]/g;
const CTRL_RE = /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g; // non-printable except \t \n \r

export function stripAnsi(text: string): string {
  return text.replace(ANSI_RE, "").replace(CTRL_RE, "");
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function Badge({
  tone,
  children,
}: {
  tone: "success" | "danger" | "muted";
  children: React.ReactNode;
}) {
  const cls =
    tone === "success"
      ? "bg-[color:var(--color-success)]/15 text-[color:var(--color-success)]"
      : tone === "danger"
        ? "bg-destructive/15 text-destructive"
        : "bg-muted text-muted-foreground";
  return (
    <span
      className={`rounded-full px-2 py-0.5 font-mono text-[9px] font-medium uppercase tracking-wider ${cls}`}
    >
      {children}
    </span>
  );
}

function OutputBlock({
  icon,
  kind,
  badge,
  children,
}: {
  icon: React.ReactNode;
  kind: string;
  badge: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-border bg-card/40">
      <div className="flex items-center gap-1.5 border-b border-border bg-card/60 px-3 py-1.5">
        <span className="text-muted-foreground">{icon}</span>
        <span className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">
          {kind}
        </span>
        <span className="ml-auto">{badge}</span>
      </div>
      <div className="p-3">{children}</div>
    </div>
  );
}

function DisplayBlock({ mime, data }: { mime: string; data: string }) {
  if (mime.startsWith("image/")) {
    return (
      <OutputBlock
        icon={<Image className="h-3 w-3" />}
        kind="image"
        badge={<Badge tone="success">ok</Badge>}
      >
        <img
          src={`data:${mime};base64,${data}`}
          alt="output"
          className="max-w-full rounded-lg border border-border"
        />
      </OutputBlock>
    );
  }

  if (mime === "text/html") {
    return (
      <OutputBlock
        icon={<Code2 className="h-3 w-3" />}
        kind="text/html"
        badge={<Badge tone="success">ok</Badge>}
      >
        {/* HTML generated by the user's local kernel */}
        <div
          className="overflow-auto text-xs"
          dangerouslySetInnerHTML={{ __html: data }}
        />
      </OutputBlock>
    );
  }

  return (
    <OutputBlock
      icon={<Code2 className="h-3 w-3" />}
      kind={mime === "text/plain" ? "text/plain" : mime}
      badge={<Badge tone="success">ok</Badge>}
    >
      <pre className="max-h-32 overflow-auto whitespace-pre-wrap font-mono text-[11px] leading-relaxed text-foreground/80">
        {mime === "text/plain" ? stripAnsi(data) : `[${mime}] ${data.slice(0, 200)}`}
      </pre>
    </OutputBlock>
  );
}

// ─── ErrorBlock ───────────────────────────────────────────────────────────────
// The kernel sends tracebacks as raw ANSI-colored strings. We strip the escape
// codes and also clean up the leading "---...---" separator lines that Jupyter
// adds but that are meaningless here.

function ErrorBlock({ text }: { text: string }) {
  const clean = stripAnsi(text)
    // remove pure separator lines (e.g. "-----------…-----------")
    .replace(/^[-─═]+\s*$/gm, "")
    // collapse 3+ consecutive blank lines into 2
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  return (
    <OutputBlock
      icon={<AlertTriangle className="h-3 w-3 text-destructive" />}
      kind="stderr"
      badge={<Badge tone="danger">error</Badge>}
    >
      <pre className="max-h-64 overflow-auto whitespace-pre-wrap font-mono text-[11px] leading-relaxed text-destructive">
        {clean}
      </pre>
    </OutputBlock>
  );
}

// ─── Main export ─────────────────────────────────────────────────────────────

interface Props {
  output: ExecResult;
}

export function CellOutput({ output }: Props) {
  const hasContent =
    output.stdout || output.stderr || output.displays.length > 0;

  if (output.status === "running") {
    return (
      <OutputBlock
        icon={<Loader2 className="h-3 w-3 animate-spin" />}
        kind="exécution en cours"
        badge={<Badge tone="muted">running</Badge>}
      >
        <p className="font-mono text-[11px] text-muted-foreground">
          Exécution de la cellule…
        </p>
      </OutputBlock>
    );
  }

  if (!hasContent) return null;

  return (
    <div className="space-y-2">
      {output.stdout && (
        <OutputBlock
          icon={<Terminal className="h-3 w-3" />}
          kind="stdout"
          badge={
            <Badge tone={output.status === "ok" ? "success" : "muted"}>ok</Badge>
          }
        >
          <pre className="max-h-48 overflow-auto whitespace-pre-wrap font-mono text-[11px] leading-relaxed text-foreground/90">
            {stripAnsi(output.stdout)}
          </pre>
        </OutputBlock>
      )}

      {output.stderr && <ErrorBlock text={output.stderr} />}

      {output.displays.map((d, i) => (
        <DisplayBlock key={i} mime={d.mime} data={d.data} />
      ))}
    </div>
  );
}
