id: extract_kafka
name: 'Extract: Apache Kafka'
description: Consomme les messages d'un topic Kafka et les dump.
category: 1. Extract
tags:
- extract
- kafka
- stream
- bigdata
code_template: "from kafka import KafkaConsumer\nimport os\n\n# [PARAM: BROKER | string]\n\
  BROKER = \"localhost:9092\"\n# [/PARAM]\n\n# [PARAM: TOPIC | string]\nTOPIC = \"\
  my_data_topic\"\n# [/PARAM]\n\n# [PARAM: MAX_MESSAGES | string]\nMAX_MESSAGES =\
  \ \"100\"\n# [/PARAM]\n\n# [PARAM: DEST_PATH | string]\nDEST_PATH = \"./data/raw/kafka_dump.jsonlines\"\
  \n# [/PARAM]\n\nprint(f\"[EXTRACT] Consommation Kafka de {TOPIC} (Broker: {BROKER})...\"\
  )\nos.makedirs(os.path.dirname(DEST_PATH), exist_ok=True)\n\ntry:\n    consumer\
  \ = KafkaConsumer(TOPIC, bootstrap_servers=BROKER, auto_offset_reset='earliest',\
  \ consumer_timeout_ms=5000)\n    \n    count = 0\n    with open(DEST_PATH, \"w\"\
  , encoding=\"utf-8\") as f:\n        for message in consumer:\n            val =\
  \ message.value.decode('utf-8')\n            f.write(val + \"\\\\n\")\n        \
  \    count += 1\n            if count >= int(MAX_MESSAGES):\n                break\n\
  \                \n    print(f\"[EXTRACT] Succès Kafka. {count} messages dumpés.\"\
  )\nexcept Exception as e:\n    print(f\"[ERREUR EXTRACT] Échec de la connexion Kafka\
  \ : {str(e)}\")\n    raise e\n\ndf = None\ntarget_name = None\ntask_type = \"unknown\"\
  \nmeta = {\"source\": \"kafka\", \"path\": DEST_PATH}\n"
illustration_mermaid: |
    graph LR
      Source[(Source)] -->|Load| Node([Extract Data])
      style Source fill:#3b82f6,stroke:#2563eb,stroke-width:2px,color:#fff
      style Node fill:#eff6ff,stroke:#3b82f6,stroke-width:2px

_metadata:
  bloc: 1
  section: 1_extract
